# Generated by Django 5.0.3 on 2024-03-07 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='student_profiles.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('snu_email', models.EmailField(max_length=255, unique=True)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_details', models.CharField(blank=True, max_length=255, null=True)),
                ('passing_year', models.IntegerField()),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=512, null=True)),
                ('projects', models.TextField(blank=True, max_length=512, null=True)),
                ('area_of_interest', models.ManyToManyField(blank=True, related_name='students', to='student_profiles.areaofinterest')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_profiles.major')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_profiles.school')),
                ('skills', models.ManyToManyField(blank=True, related_name='students', to='student_profiles.skill')),
            ],
        ),
    ]
