# Generated by Django 5.0.3 on 2024-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('SOE', 'School of Engineering'), ('SME', 'School of Management and Entrepreneurship'), ('SHSS', 'School of Humanities and Social Sciences'), ('SNS', 'School of Natural Sciences')], max_length=255),
        ),
    ]
